"""followers

Revision ID: 973033c4e049
Revises: 7468a6b03e8b
Create Date: 2019-06-03 17:16:54.422327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973033c4e049'
down_revision = '7468a6b03e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
